// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7o5CRov2dlsM1454hZvJWtXD3V1IFj-k',
    appId: '1:432087736774:web:478627bfa8fd89881992c7',
    messagingSenderId: '432087736774',
    projectId: 'ialfm-prayer-times',
    authDomain: 'ialfm-prayer-times.firebaseapp.com',
    storageBucket: 'ialfm-prayer-times.firebasestorage.app',
    measurementId: 'G-HSFBTP68K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpE4D4Ss3XjloyECb6rFrmHwfbXTjSBek',
    appId: '1:432087736774:android:4b5e7082ce4cd7891992c7',
    messagingSenderId: '432087736774',
    projectId: 'ialfm-prayer-times',
    storageBucket: 'ialfm-prayer-times.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw1Pmpffpdkm_I27iAJ-6GjsgKuLgpyW4',
    appId: '1:432087736774:ios:24fbf9d99f5920091992c7',
    messagingSenderId: '432087736774',
    projectId: 'ialfm-prayer-times',
    storageBucket: 'ialfm-prayer-times.firebasestorage.app',
    iosBundleId: 'org.ialfm.prayertimes',
  );

}